### ISSUE TITLE
Crashing OBJ Load

### ISSUE THREAD

**Issue by delaneyj** [g3n/engine#101]
I'm testing loading larger files that are exported from Blender and running into a situation similar to https://github.com/g3n/engine/issues/8.  

When I load this OBJ/MTL https://drive.google.com/open?id=116J2zJAjiiSIUPvUl3WadIzEnm_Tz19E
using 
```
testObjName := "falcon"
	dec, err := obj.Decode(
		fmt.Sprintf("testdata/%s.obj", testObjName),
		fmt.Sprintf("testdata/%s.mtl", testObjName),
	)
```

I get 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x567bfb]
goroutine 1 [running, locked to thread]:
github.com/g3n/engine/loader/obj.(*Decoder).parseUsemtl(0xc0005da0c0, 0xc0005d8030, 0x1, 0x1, 0x0, 0x0)
	/home/delaney/go/src/github.com/g3n/engine/loader/obj/obj.go:565 +0x12b
github.com/g3n/engine/loader/obj.(*Decoder).parseObjLine(0xc0005da0c0, 0xc001d31480, 0x13, 0x0, 0x0)
	/home/delaney/go/src/github.com/g3n/engine/loader/obj/obj.go:363 +0xc2d
github.com/g3n/engine/loader/obj.(*Decoder).parseObjLine-fm(0xc001d31480, 0x13, 0x0, 0x0)
	/home/delaney/go/src/github.com/g3n/engine/loader/obj/obj.go:130 +0x4b
github.com/g3n/engine/loader/obj.(*Decoder).parse(0xc0005da0c0, 0x6d7400, 0xc0005bc040, 0xc000683ab0, 0x0, 0x0)
	/home/delaney/go/src/github.com/g3n/engine/loader/obj/obj.go:312 +0x1c9
github.com/g3n/engine/loader/obj.DecodeReader(0x6d7400, 0xc0005bc040, 0x6d7400, 0xc0005bc048, 0x0, 0x0, 0x0)
	/home/delaney/go/src/github.com/g3n/engine/loader/obj/obj.go:130 +0x2d8
github.com/g3n/engine/loader/obj.Decode(0xc0005dc020, 0x13, 0xc0005dc040, 0x13, 0x0, 0x0, 0x0)
	/home/delaney/go/src/github.com/g3n/engine/loader/obj/obj.go:108 +0x464
```

Is this a bug or some unsupported variant?

**Comment by quillaja** [comment]
I think this is related to, and will be fixed by, my PR #116 . The OBJ decoder doesn't fully support all the ways in which things in OBJ can be optional. In this case, my guess is your blender-produced OBJ doesn't have a `o` or `g` (object/group) line in it. Currently that causes a nil pointer error when parsing, as the decoder assumes a group was created previously. @delaneyj @danaugrs

**Comment by danaugrs** [comment]
@delaneyj @quillaja's PRs have been merged - can you get latest and try again?

**Comment by quillaja** [comment]
I think the recently merged changes fixed this issue. I just got around to opening the model in the `g3nview` demo program build with the current master and was able to open the above linked OBJ without problem (though many warnings about `l` fields not being supported).

I'd say it's probably safe to close this issue.

![falcon](https://user-images.githubusercontent.com/17558269/56460899-d26dd600-635e-11e9-9b36-4c595c4e828b.png)

**Comment by danaugrs** [comment]
Great!
