### ISSUE TITLE
CrossCompile for windows from a linux machine

### ISSUE THREAD

**Issue by rami-dabain** [g3n/engine#107]
Is there a correct way to build for windows from a linux machine?
Whenever I try it it gives me:

> ..... glfw.go:11:2: build constraints exclude all Go files in /go/src/github.com/go-gl/glfw/v3.2/glfw

I'm building with:
`GOOS=windows GOARCH=amd64 go build`

**Comment by racerxdl** [comment]
You will need to install mingw32 cross compiler and explicity define CC and CXX variables, as well CGO_ENABLED=1

**Comment by n005** [comment]
You may install gcc-mingw-w64:
`sudo apt-get install gcc-mingw-w64`
An compile using:
`GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc go build
`
