### ISSUE TITLE
gui: Default font metrics

### ISSUE THREAD

**Issue by jamiec7919** [g3n/engine#11]
Is there a recommended way of getting the default font metrics for a piece of text?  Possible I've missed it somewhere but I see font.MeasureText which would work but how to get the default font in use?

**Comment by leonsal** [comment]
Currently the font object of a `gui.Label` is inaccessible externally. We will review this, probably adding some method to get the font metrics of the font used by `gui.Label`. But if you need only the size of the text (width and height) you can use `width, height := label.Size()`. When a `gui.Label` is created it has the exact size of the  text.

**Comment by danaugrs** [comment]
As of Apr 21st 2018 (https://github.com/g3n/engine/commit/3d9211ec5fff557af1e3ef84e3620304dbdf5836) you can obtain the metrics of a label via `label.Font().Metrics()`.
