### ISSUE TITLE
Support for Go Modules

### ISSUE THREAD

**Issue by udhos** [g3n/engine#117]
It would be nice to support Go Modules so we could build g3n out of GOPATH.

"Our aim is for Go 1.13, scheduled for August 2019, to enable module mode by default (that is, to change the default from auto to on) and deprecate GOPATH mode. In order to do that, we’ve been working on better tooling support along with better support for the open-source module ecosystem."
https://blog.golang.org/modules2019

Full details on Go Modules: https://github.com/golang/go/wiki/Modules

**Comment by danaugrs** [comment]
@udhos Oi fellow Paulistano. Thanks for the contribution! I've updated G3N to use go modules in https://github.com/g3n/engine/commit/bb06976c0b256516a3219c85cab68a554a5872ff using the current latest versions of the dependencies and also updated the README in https://github.com/g3n/engine/commit/156892788b2b18916a7236d4f5a0748926f31fb1 somewhat based on your PR.

**Comment by rami-dabain** [comment]
For some reason the /app is non existing in the module when adding it as described in https://github.com/g3n/engine/commit/156892788b2b18916a7236d4f5a0748926f31fb1

```
go: finding github.com/g3n/engine/app latest
build command-line-arguments: cannot load github.com/g3n/engine/app: cannot find module providing package github.com/g3n/engine/app

```

**Comment by danaugrs** [comment]
Are you trying to run your own modules-based application using G3N? If so do a `go get github.com/g3n/engine@master` and try again.
