### ISSUE TITLE
Compile error when compiling example

### ISSUE THREAD

**Issue by olofwalker** [g3n/engine#120]
Hi,

1. I created a new empty project
2. Copy pasted in the "blue torus" example app into a file
3. Ran dep init / dep ensure
4. When building I got the following:

```
vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:10: fatal error: glfw/src/context.c: No such file or directory
 #include "glfw/src/context.c"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

`Ubuntu 18.04` with the dependencies installed using `apt` as suggested in the readme and `go1.12.1 linux/amd64`

**Comment by leonsal** [comment]
The path starting with "vendor/github.com/go-gl/glfw/...."  in the error message is strange.
GLFW is a dependency but we do not use vendor directories.
Could this be an artifact left by  "dep" ?
  
Have you tried to install G3ND (the G3N demo ?)
> go get -v github.com/g3n/g3nd
