### ISSUE TITLE
Support for glfw icon

### ISSUE THREAD

**Issue by Jldevictoria** [g3n/engine#121]
Do you have plans to add support for glfw window icons?

This seems to be available within glfw (see glfwSetWindowIcon(window, 0, NULL);)

https://www.glfw.org/docs/latest/window_guide.html#window_icon

**Comment by danaugrs** [comment]
Sure! As soon as we are done targeting web assembly I'll take a look at this 😄

**Comment by danaugrs** [comment]
The core engine has been refactored in the [wasm branch](https://github.com/g3n/engine/tree/wasm) for WebAssembly support and now we expose the GLFW window directly so users have full access to the GLFW API. The branch should be merged at some point soon.
