### ISSUE TITLE
matrix transpose, take advantage of Go's great swap feature

### ISSUE THREAD

**Issue by rcoreilly** [g3n/engine#123]
Matrix4 Transpose() can be more efficiently written as:

```Go
	m[1], m[4] = m[4], m[1]
	m[2], m[8] = m[8], m[2]
	m[6], m[9] = m[9], m[6]
	m[3], m[12] = m[12], m[3]
	m[7], m[13] = m[13], m[7]
	m[11], m[14] = m[14], m[11]
```

and likewise for Matrix3:

```Go
	m[1], m[3] = m[3], m[1]
	m[2], m[6] = m[6], m[2]
	m[5], m[7] = m[7], m[5]
```

btw thanks for the great math library! :)

**Comment by danaugrs** [comment]
Thanks! Fixed by https://github.com/g3n/engine/commit/afe309ef9840a5fa4b12b849db2fd5f55c03bddb.

**Comment by rcoreilly** [comment]
FYI: I stole all your excellent math32 code and rewrote using pure value semantics (except for matricies) instead of pointer-based, which allows for much simpler expression semantics.  For my money that benefit outweighs any performance diff -- though I never benchmarked anything. https://github.com/goki/gi/tree/master/mat32 in case you're interested.
