### ISSUE TITLE
loader/obj/obj.go parseSmooth should support numeric values > 1

### ISSUE THREAD

**Issue by hrak** [g3n/engine#125]
Importing a .obj file with smoothing groups (f.e. [this one](https://github.com/xiuyansyu/animation/blob/master/Bigmax_White_OBJ.obj)) results in a `panic: 's' with invalid value in line:xxx`

According to the [.obj spec](http://www.martinreddy.net/gfx/3d/OBJ.spec) the value for 's' can be anything numeric + 'on' and 'off'

**Comment by amlwwalker** [comment]
any word on this?

**Comment by danaugrs** [comment]
Fixed via https://github.com/g3n/engine/commit/4b371a87a0c103e728c91975519a508f4f6c81c8
