### ISSUE TITLE
Chrome for desktop and Mobile

### ISSUE THREAD

**Issue by ghost** [g3n/engine#128]
It would be possible to use this with go-flutter and get all the advanced form and 3d aspects 

The 2d and 3d canvas can be streamed into from 3gn.

https://github.com/go-flutter-desktop/go-flutter

It's very easy.

There is a video conferencing golang app that uses flutter and it uses the same approach of rendering directly into the flutter texture canvas.

Flutter handles all gesture, mouse, keyboard aspects and passes them to your golang plugin. Go-flutter already does this for you 

@Thommil
You can do the same for mobiles also. Just use gomobile as a flutter plugin.

Also dart FFI support lsnded.
This means you can compile your golang code to a shared c lib and flutter uses it as a plugin on mobile and desktop with higher performance.

Flutter also runs on web. The usage of wasm as plugins is still in the works but I expect it will happen.

https://api.flutter.dev/flutter/widgets/Texture-class.html

https://medium.com/@germansaprykin/opengl-with-texture-widget-f919743d25d9

**Comment by danaugrs** [comment]
It might be interesting to explore using flutter. Right now G3N is essentially working on the web already via WebAssembly in the [wasm branch](https://github.com/g3n/engine/tree/wasm). It's going to be merged at some point soon.
