### ISSUE TITLE
Trouble loading models

### ISSUE THREAD

**Issue by sashabaranov** [g3n/engine#129]
Hi,

I'm trying to load [this](https://opengameart.org/content/covered-well) model. I've exported it with Blender 2.79 (2.80 did not export correctly) to .dae and .obj formats.

MacOS preview does show .dae file with correct texturing, however loading it with g3n does not show up correct result. I've loaded files in the same way g3nview does it and get similar to g3nview results:

![image](https://user-images.githubusercontent.com/677093/64285206-fb84b100-cf63-11e9-96e2-a1e216833948.png)

obj-loader fails with `panic: open /home/icu/Ubuntu: no such file or directory` on `NewGroup()`. Which is super strange as I'm working on a mac.

I'm attaching .blend, .obj and .dae to this issue.

[well.zip](https://github.com/g3n/engine/files/3576185/well.zip)

**Comment by danaugrs** [comment]
Hi! To fix the `obj` error, you can open `well.coveredopen.mtl` with a text editor and you'll see:

```mtl
# Blender MTL File: 'well.coveredopen.blend'
# Material Count: 1

newmtl well.covered.O.ma
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.800000
Ks 0.500000 0.500000 0.500000
Ke 0.250000 0.250000 0.250000
Ni 1.000000
d 1.000000
illum 2
map_Kd /home/icu/Ubuntu One/workshop/Animals/settings/generic.props/well/well.O.jpg
map_Bump -bm -0.500000 /home/icu/Ubuntu One/workshop/Animals/settings/generic.props/well/well.O.nor.jpg
map_Ks /home/icu/Ubuntu One/workshop/Animals/settings/generic.props/well/well.O.spec.jpg
```

You should update those texture paths to match the actual texture paths on your system. You could do that directly in the file or in blender and re-export.

When loading the collada model, try placing the textures and `dae` file in the same directory `g3nview` is in.

With that said, I recommend using the [glTF](https://www.khronos.org/gltf/) format (you can export it from blender 2.80).

Unfortunately `g3nview` is a bit outdated and doesn't accept glTF (PR welcome!).

[Here's an example that loads arbitrary glTF models](https://github.com/g3n/g3nd/blob/master/loader/gltf.go).

**Comment by sashabaranov** [comment]
@danaugrs Thank you for a tip, it worked out perfectly! I've actually started with glTF, but Blender 2.80 was not opening this model properly.

**Comment by danaugrs** [comment]
@sashabaranov Great that it's working! Let me know if you have any other questions or encounter any other issues.
