### ISSUE TITLE
material blending

### ISSUE THREAD

**Issue by SavostinVladimir** [g3n/engine#13]
Hi. I try to use material blending by example from your demo-programm. I want to create sun shine imitation. This is my code:
```
//CREATION OF SUN SHINE
		tex, err := texture.NewTexture2DFromImage("data/images/lensflare0_alpha.png")
		if err != nil {
			log.Fatal("Error loading texture: %s", err)
		}
	geo1 := geometry.NewPlane(10, 10, 1, 1)
	defer geo1.Dispose()

			material := material.NewPhong(math32.NewColor(1, 1, 1))
			material.SetOpacity(1)
			material.AddTexture(tex)
			material.SetBlending(2)
			mesh := graphic.NewMesh(geo1.Incref(), material)
			mesh.SetPosition(0, 0, -10)
			scene.Add(mesh)
```
but I have next result:
![default](https://user-images.githubusercontent.com/27097483/27351512-6f955646-561f-11e7-9226-d5b8d05e1e78.png)
If I change blending to various values from 0 up to 4, it shows a black square with or without shine.
I need the square to become transparent and I only saw the sun. How can i do this

**Comment by leonsal** [comment]
Try to remove the `defer geo1.Dispose()` line.
`Dispose()` releases the OpenGL resources used by an object (in this case the geometry).
Should be used only after the object is removed from the scene and is not going to be used anymore.

**Comment by SavostinVladimir** [comment]
I tried, but the result is the same

**Comment by danaugrs** [comment]
@SavostinVladimir I added a sun sprite to the earth_shader demo. Check it out!
