### ISSUE TITLE
Camera SetDirectionVec

### ISSUE THREAD

**Issue by moethu** [g3n/engine#137]
Hi, I'm trying to set my camera direction using SetDirectionVec(), assuming it works the same way as SetPositionVec() which works fine. But somehow my camera doesn't get updated.
```
	P := math32.Vector3{X: 0, Y: -600, Z: 0}
	log.Println(app.Camera().GetCamera().Direction())
	app.Camera().GetCamera().SetDirectionVec(&P)
	log.Println(app.Camera().GetCamera().Direction())
```
According to the log everything worked out fine, but the camera doesn't change. Also I tried to send updateMatrix() just to be sure.
```
{68.875694 8.3433485 40.36918}
{0 -600 0}
```
Any ideas? Do I have to trigger something else?

**Comment by danaugrs** [comment]
Hi - the direction is separate from the position - the API is confusing there and probably needs improvement. You should use `app.Camera().GetCamera().LookAt(&target)` providing a `target` position you want the camera to look at.

**Comment by moethu** [comment]
@danaugrs any plans to add clipping planes? If not, I might give it a shot (http://glbook.gamedev.net/GLBOOK/glbook.gamedev.net/moglgp/advclip.html)

**Comment by danaugrs** [comment]
@moethu not currently - sounds good!
