### ISSUE TITLE
Vulkan

### ISSUE THREAD

**Issue by jessezwd** [g3n/engine#140]
Hi there, when will you move to Vulkan?

**Comment by danaugrs** [comment]
Hi! There are no plans to support Vulkan directly but it should be possible to use Vulkan as a backend with an OpenGL API via something like [GLOVE](https://github.com/Think-Silicon/GLOVE) or [VKGL](https://github.com/kbiElude/VKGL).

**Comment by jessezwd** [comment]
Cool!
