### ISSUE TITLE
q: simple box

### ISSUE THREAD

**Issue by glycerine** [g3n/engine#142]
sorry for a really simple, basic question: I want to draw a box on a canvas, and color it red. Could you share an example of using g3n/engine for this? thanks!

**Comment by kryton9** [comment]
package main

import (
"github.com/g3n/engine/geometry"
"github.com/g3n/engine/graphic"
"github.com/g3n/engine/light"
"github.com/g3n/engine/material"
"github.com/g3n/engine/math32"
"github.com/g3n/engine/util/application"
)

func main() {
app, _ := application.Create(application.Options{
Title:  "Cube",
Width:  800,
Height: 600,
})

// Create a blue torus and add it to the scene
geom := geometry.NewCube(2) //NewTorus(1, .4, 12, 32, math32.Pi*2)
mat := material.NewPhong(math32.NewColor("Red"))
cubeMesh := graphic.NewMesh(geom, mat)
app.Scene().Add(cubesMesh)
torusMesh.SetPosition(1, 0, 1)
// Add lights to the scene
ambientLight := light.NewAmbient(math32.NewColor("white"), 0.8)
app.Scene().Add(ambientLight)
pointLight := light.NewPoint(math32.NewColor("white"), 5.0)
pointLight.SetPosition(1, 2, 2)
//app.Scene().Add(pointLight)
torusMesh.Add(pointLight)

// Add an axis helper to the scene size, width
axis := graphic.NewAxisHelper2(100, 2) //0.5
app.Scene().Add(axis)

// Add grid GridHelper
grid := graphic.NewGridHelper2(200, 1, 0.125, math32.NewColor("darkgrey"))
app.Scene().Add(grid)

app.CameraPersp().SetPosition(2, 2, 3)
app.CameraPersp().LookAt(math32.NewVector3(0, 0, 0))
app.Run()
}

**Comment by glycerine** [comment]
awesome.

is this on a branch?

box.go:9:2: cannot find package "github.com/g3n/engine/util/application" in any of:
    /usr/local/go/src/github.com/g3n/engine/util/application (from $GOROOT)

**Comment by danaugrs** [comment]
@kryton9 the example you posted is for an old version of g3n. Also I think @glycerine meant a 2D box? Can you confirm @glycerine?

**Comment by glycerine** [comment]
yes, a 2D box is perfect. Thanks guys!

**Comment by kryton9** [comment]
Sorry the last version had bugs in my haste to respond.

This one works:

package main

import (
"github.com/g3n/engine/geometry"
"github.com/g3n/engine/graphic"
"github.com/g3n/engine/light"
"github.com/g3n/engine/material"
"github.com/g3n/engine/math32"
"github.com/g3n/engine/util/application"
)

func main() {
app, _ := application.Create(application.Options{
Title:  "Cube",
Width:  800,
Height: 600,
})

geom := geometry.NewCube(2)
mat := material.NewPhong(math32.NewColor("Red"))
cubeMesh := graphic.NewMesh(geom, mat)
app.Scene().Add(cubeMesh)
cubeMesh.SetPosition(1, 0, 1)
// Add lights to the scene
ambientLight := light.NewAmbient(math32.NewColor("white"), 0.8)
app.Scene().Add(ambientLight)
pointLight := light.NewPoint(math32.NewColor("white"), 5.0)
pointLight.SetPosition(1, 2, 2)
//app.Scene().Add(pointLight)
cubeMesh.Add(pointLight)

// Add an axis helper to the scene size, width
axis := graphic.NewAxisHelper2(100, 2) //0.5
app.Scene().Add(axis)

// Add grid GridHelper
grid := graphic.NewGridHelper2(200, 1, 0.125, math32.NewColor("darkgrey"))
app.Scene().Add(grid)

app.CameraPersp().SetPosition(2, 2, 3)
app.CameraPersp().LookAt(math32.NewVector3(0, 0, 0))
app.Run()
}

**Comment by danaugrs** [comment]
@glycerine I'll put an example together and post here
@kryton9 That's still outdated

**Comment by kryton9** [comment]
Thanks, just getting back into Go and G3N will need to update.

**Comment by glycerine** [comment]
@kryton9 Thanks Kent. It looks like the latest g3n doesn't have util/application any more; could you update your example?  Also, yes, I'm trying to do a flat, 2D box.

**Comment by danaugrs** [comment]
@glycerine To draw 2D components you can use the [`Panel`](https://godoc.org/github.com/g3n/engine/gui#Panel) object. All GUI widgets are based on `Panel`. Here's a complete working example:

```go
package main

import (
	"github.com/g3n/engine/app"
	"github.com/g3n/engine/camera"
	"github.com/g3n/engine/core"
	"github.com/g3n/engine/gls"
	"github.com/g3n/engine/gui"
	"github.com/g3n/engine/math32"
	"github.com/g3n/engine/renderer"
	"github.com/g3n/engine/window"
	"time"
)

func main() {

	// Create application and scene
	a := app.App()
	scene := core.NewNode()

	// Set the scene to be managed by the gui manager
	gui.Manager().Set(scene)

	// Create perspective camera
	cam := camera.New(1)
	cam.SetPosition(0, 0, 3)
	scene.Add(cam)

	// Set up orbit control for the camera
	camera.NewOrbitControl(cam)

	// Set up callback to update viewport and camera aspect ratio when the window is resized
	onResize := func(evname string, ev interface{}) {
		// Get framebuffer size and update viewport accordingly
		width, height := a.GetSize()
		a.Gls().Viewport(0, 0, int32(width), int32(height))
		// Update the camera's aspect ratio
		cam.SetAspect(float32(width) / float32(height))
	}
	a.Subscribe(window.OnWindowSize, onResize)
	onResize("", nil)

	// ============================================
	// Create 2D "box" with specified size, set its position and color it blue
	// ============================================
	pan := gui.NewPanel(100, 30)
	pan.SetPosition(10, 10)
	pan.SetColor(math32.NewColor("blue"))
	scene.Add(pan)
	// ============================================

	// Set background color to gray
	a.Gls().ClearColor(0.5, 0.5, 0.5, 1.0)

	// Run the application
	a.Run(func(renderer *renderer.Renderer, deltaTime time.Duration) {
		a.Gls().Clear(gls.DEPTH_BUFFER_BIT | gls.STENCIL_BUFFER_BIT | gls.COLOR_BUFFER_BIT)
		renderer.Render(scene, cam)
	})
}
```
Let me know if you have any further questions!

**Comment by danaugrs** [comment]
@kryton9 Thanks for trying to help out with the issues - it's much appreciated!

**Comment by kryton9** [comment]
My pleasure, sorry I was out of date.
