### ISSUE TITLE
ld: warning: object file ... was built for newer OSX version (10.15) than is being linked (10.14)

### ISSUE THREAD

**Issue by seatonullberg** [g3n/engine#146]
My application build is fine on Manjaro-Xfce 18.1.1 but when I tried to build on my MacBook Pro running Catalina 10.15 the gui edit fields are unresponsive and the camera angle is changed. Is this unresolvable without downgrading the mac OS?

**Comment by danaugrs** [comment]
This should be fixed in the latest version. Sorry for the delay.
