### ISSUE TITLE
Specify app options

### ISSUE THREAD

**Issue by bdoms** [g3n/engine#165]
I'm just getting started with g3n but really liking what I see. When I was trying to create my own app, it looks like I can't specify window options. Looking through some old examples it looks like it was previously possible by passing in `application.Options`, which held things like the window width and height. But that seems to have disappeared now.

Am I missing something? Or is https://github.com/g3n/engine/blob/master/app/app-desktop.go only meant as an example? If that's the case I think mentioning that clearly in the code and updating the docs (e.g. https://github.com/g3n/engine/wiki/Getting-Started-(WIP) ) would be a good idea.

**Comment by danaugrs** [comment]
Hi! You can modify anything about the window after it's created. For example:
```go
glfwWin := window.Get().(*window.GlfwWindow) // Assert that it's a GlfwWindow (only works on desktop)
glfwWin.SetSize(500, 400) (
glfwWin.SetTitle("MyAwesomeTitle")
```
G3N's `GlfwWindow` type embeds GLFW's `Window` type, so you can call any method from GLFW's `Window` type directly: https://godoc.org/github.com/go-gl/glfw/v3.3/glfw#Window.
The snippet above will work as long as you call `myApp := app.App()` first (which calls `window.Init(...)`).
The idea is that when we support more platforms in the future, all you will have to do for your application to run on all of them is to move the platform specific code like the snippet above into a file with the appropriate [build tag](https://golang.org/pkg/go/build/#hdr-Build_Constraints).
Let me know if you have any other questions!

**Comment by bdoms** [comment]
That works, thanks!

My only concern is that initializing the window at a different resolution creates a flash of that window before the size is changed. It's subtle, but I can notice it. Is the idea with the build targets that they'll read the configuration data *before* ever initializing the window, and thus this is a temporary situation we don't need to worry about?

**Comment by danaugrs** [comment]
Window `width`, `height`, and `title` are now required when creating an App so there's no flash.
```go
func App(width, height int, title string) *Application { ... }
```
For all other window options please use the method described above.

**Comment by snoweuph** [comment]
@danaugrs I'm rn giving g3n a try, and I noticed that `Application` is still opaque, and you no longer pass those options to `app.App`.

For anybody exploring the Docs, they wouldn't come to the idea, that they can just cast the `window.IWindow` to a `*window.GlfwWindow`.
took me 2 hours of manually exploring the examples, doc and wiki, to find this issue.
The Wiki btw still speaks from an `app.Create` that takes `app.Options`.

Could you maybe add this into the docs, or add a method like `AsGLFWWindow` to the `IWindow`, which would explicitly state that they can be converted?
