### ISSUE TITLE
Horizontal FOV is ignored

### ISSUE THREAD

**Issue by metalim** [g3n/engine#173]
https://github.com/g3n/engine/blob/78541849abfd586a7e5ab75596c5be5f1e843344/camera/camera.go#L245-L249

Last line sets FOV to stored one, ignoring the calculated FOV.

Also, calculation in line 247 doesn't seem to be correct, as multiplying by aspect reduces FOV even more when shrinking window horizontally.

**Comment by metalim** [comment]
I made duct tape fix by adding new function and using it for horizontal FOV instead of `MakePerspective`. Not sure how to do it properly:
```go
// in matrix4.go
func (m *Matrix4) MakePerspectiveH(fovH, aspect, near, far float32) *Matrix4 {
	xmax := near * Tan(DegToRad(fovH*0.5))
	xmin := -xmax
	ymin := xmin / aspect
	ymax := xmax / aspect
	return m.MakeFrustum(xmin, xmax, ymin, ymax, near, far)
}

// in camera.go
			if c.axis == Horizontal {
				c.projMatrix.MakePerspectiveH(c.fov, c.aspect, c.near, c.far)
			} else {
				c.projMatrix.MakePerspective(c.fov, c.aspect, c.near, c.far)
			}
```

**Comment by danaugrs** [comment]
@metalim Nice catch! Thanks for the heads up 😄
I've fixed it here, using `MakeFrustum` directly: https://github.com/g3n/engine/commit/39ccc1c74ee54596f756530d3c119d8d102f50d6
