### ISSUE TITLE
How to render to buffer and read it from Go?

### ISSUE THREAD

**Issue by metalim** [g3n/engine#186]
Not an issue, but rather a question.

How to render to buffer and then read it's data from Go code? For GPU terrain generation.

**Comment by etherealmachine** [comment]
I did something similar in https://github.com/etherealmachine/novaterra, which both has a compute shader that does a pure GPU operation on the terrain texture and also reads from a texture in Go to do mouse picking (https://github.com/etherealmachine/novaterra/blob/39b8bee8c43b5035b79b27f1eebdfbaef19951d4/main.go#L353).

**Comment by etherealmachine** [comment]
Oh, I also forgot that I had to fork and add some methods to the GLS class to make this work. I've turned that fork into https://github.com/g3n/engine/pull/190.

**Comment by danaugrs** [comment]
This was implemented in https://github.com/g3n/engine/pull/247.
