### ISSUE TITLE
how can disable mouse cursor

### ISSUE THREAD

**Issue by erdemakyildiz** [g3n/engine#188]
I called but couldn't find it. can you help me

**Comment by danaugrs** [comment]
Hi, sure! I haven't tested this but it should be:
```go
window.Get().(window.GlfwWindow).SetInputMode(window.CursorInputMode, window.CursorHidden)
```
[This method is available on `go-gl/glfw.Window`.](https://godoc.org/github.com/go-gl/glfw/v3.3/glfw#Window.SetInputMode)


To break it down. First we obtain the `IWindow` singleton by calling `window.Get()`.
You could also obtain your `IWindow` singleton by callling `app.App().Window()`.
Then we assert that it is of type `window.GlfwWindow`.
Then we call `SetInputMode(...)` following the `go-gl/glfw` API.

**Comment by erdemakyildiz** [comment]
Thank you for answer. I changed a little but it worked.

`window.Get().(*window.GlfwWindow).SetInputMode(glfw.CursorMode, glfw.CursorDisabled)`
