### ISSUE TITLE
js.TypedArrayOf has been deprecated - go 1.14

### ISSUE THREAD

**Issue by shravanshetty1** [g3n/engine#191]
https://go-review.googlesource.com/c/go/+/177537/

The above function needs to be replaced in the codebase to allow compilation

**Comment by DamianImrich** [comment]
Support for Wasm go1.13+ was added in #198. It allows compilation on both old versions of go using TypedArrayOf and on new ones using SliceHeader.
This issue definitely needs to be linked to PR #198

**Comment by danaugrs** [comment]
Merged! Thanks @DamianImrich!
