### ISSUE TITLE
How to raise fps cap?

### ISSUE THREAD

**Issue by oilboi** [g3n/engine#195]
I can't find anywhere in the docs on how to raise the fps cap. I'd love to know :D

**Comment by DamianImrich** [comment]
G3n doesn't have implemented framerate capping. It's the V-Sync. Your monitor runs typically at 60 Hz, so there's no point in rendering more frames.

On desktop you can disable V-Sync by using SetSwapInterval method in GlfwWindow
`window.Get().(*window.GlfwWindow).SetSwapInterval(0)`

**Comment by danaugrs** [comment]
Hi @oilboi, G3N provides a [FrameRater ](https://github.com/g3n/engine/blob/master/util/framerater.go) util but doesn't use it internally.
[G3ND](https://github.com/g3n/g3nd) uses it here: https://github.com/g3n/g3nd/blob/master/app/app.go#L138.
By default G3ND displays both the current FPS (capped) and the potential FPS (uncapped) separated by a forward slash.
