### ISSUE TITLE
Wasm crashes on FrameRater.Wait()

### ISSUE THREAD

**Issue by DamianImrich** [g3n/engine#199]
Compilation goes without error but when I instantiate wasm first frame is rendered and then frameRater.Wait() is called and throws error in browser console
`fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:`

On desktop it is working as expected.

**Comment by DamianImrich** [comment]
I tried it with #198 and go 1.14 and it is working as expected. No deadlock, no error and fps calculation is working well.
I think it was just some sort of bug in channels in go1.12 wasm compiler.
Maybe we can fix this just by including go 1.13+ wasm support and changing go.mod go version.

**Comment by danaugrs** [comment]
I've made the suggested change to support only Go 13+ in https://github.com/g3n/engine/commit/0e39060fc5a9794ff5c1eae1eae36280fa46e125.
Please let me know if you encounter any other issues 😄
