### ISSUE TITLE
Error compiling Fragment Shader

### ISSUE THREAD

**Issue by jeffallen** [g3n/engine#2]
Getting crashes with messages like:

15:44:13.673492:F:G3ND:Render error: Error compiling Fragment Shader: 0:42(26): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later

The code around line 42 is:

```
37:    // Combine all texture colors and opacity
38:    for (int i = 0; i < 1; i++) {
39:        if (MatTexVisible[i] == false) {
40:            continue;
41:        }
42:        vec4 texcolor = texture(MatTexture[i], FragTexcoord * MatTexRepeat[i] + MatTexOffset[i]);
43:        if (i == 0) {
44:            texCombined = texcolor;
45:        } else {
46:            texCombined = mix(texCombined, texcolor, texcolor.a);
47:        }
48:    }

```

The fix is probably to unroll the loop. But this will require re-working the template code to use {{range}} which is more than I can get into right now.

**Comment by leonsal** [comment]
Congratulations ! Your patch allowed me to run G3ND in an old Linux laptop
which I thought couldn't support shader based OpenGL.

Thanks and best regards.
