### ISSUE TITLE
Tag v0.1.0 does not include the app directory

### ISSUE THREAD

**Issue by aceeric** [g3n/engine#200]
Folks, the v0.1.0 tag doesn't include the app directory. This makes it impossible to include G3N as a go module:

```
module myproject

go 1.14

require (
	github.com/g3n/engine v0.1.0
)
```

Then:
```
package myapp
import (
    ...
    "github.com/g3n/engine/app"
    ...
)
```
In addition, in the 0.1.0 tag the `glfwWindow` struct is not visible outside the package, whereas in master, it is. Please consider adding a new tag (0.2.0?) from master.

**Comment by danaugrs** [comment]
Hi @aceeric! You can `go get github.com/g3n/engine@master` and it will work. I'll add a new version tag soon.

**Comment by aceeric** [comment]
Ahh. Thank you.

**Comment by harbdog** [comment]
v0.1.0 is still the only tag available, it would be convenient to be able to get newer versions without using @master
