### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by 68696c6c** [g3n/engine#205]
I am a very experienced web developer with several years of experience with Go specifically, and I've done some HTML canvas ray-tracing and WebGL stuff before so I'm somewhat familiar with the basics of graphics, but I'm very new to both graphics in Go and OpenGL so forgive me if this is an ignorant question.

The readme for g3n/engine says I need to install some C libraries on my system first.  On one hand, that makes sense; the go-gl library you are using needs those C libraries.  However, this requirement is surprising because the other 3d framework I've been playing around with, https://github.com/goki/gi, is also built on go-gl but does not have this requirement.  Their examples work out of the box on my linux machine (arch btw) without having to install anything.  The g3n examples so far, do not (I can provide more details if that ends up being relevant but I think my question is mostly conceptual).

I've read through the go-gl source code a bit and I'm familiar enough with the concepts to understand why a graphics program in Go would have this requirement.  I'm actually more surprised that goki/gi _doesn't_ have this requirement than that you do.  I'm sure there is a reason why g3n takes a different approach, but I am too much of a n00b to figure it out on my own.

So my question is:

If I'm understanding things correctly, it seems to be possible to use go-gl without requiring the user to install any C dependencies.  So, why does g3n require the user to install them when other frameworks don't?  G3n seems relatively mature so I assume there is some good reason I'm missing, perhaps related to cross-platform compatibility or performance?  Or am I totally misunderstanding something here?  

Additionally, if I write a game in Go using g3n, does someone that wants to play my game need to install these dependencies too?

**Comment by gremour** [comment]
From the GoKi readme: `based originally on the Shiny drivers, now using go-gl/glfw, and supporting MacOS, Linux, and Windows.`. So it seems they've also switched to glfw (which depends on CGO).

Shiny drivers seems to be pure Go implementation of OpenGL driver. It's however a tremendous feat to build and maintain a full-fledged native Go OpenGL driver with a full set of OpenGL features. Glfw is a Go binding of C library that fully supports OpenGL.

Hope that answers your question.

> Additionally, if I write a game in Go using g3n, does someone that wants to play my game need to install these dependencies too?

I suppose if you ship all the required DLLs with your executable, it should run.

**Comment by danaugrs** [comment]
I hope @gremour's answer helped you. Please let us know if you have any more questions @68696c6c.
