### ISSUE TITLE
Unable to configure App window title or size on creation

### ISSUE THREAD

**Issue by ekuusi** [g3n/engine#209]
`app-desktop.go` has the following default constants that are used when calling `app.App()`:

```// Desktop application defaults
const (
	title  = "G3N Application"
	width  = 800
	height = 600
)
```

I can't find a way to change these defaults. On MacOS I'm stuck with the default "G3N Application" title for any application I create with G3N. Am I missing something? I don't see any way to override the default width, height or title:

```
// App returns the Application singleton, creating it the first time.
func App() *Application {
	// Return singleton if already created
	if a != nil {
		return a
	}
	a = new(Application)
	// Initialize window
	err := window.Init(width, height, title)
	if err != nil {
		panic(err)
	}
...
```

**Comment by danaugrs** [comment]
You can change the title (and any other property of the window) at any time after creation using the appropriate GLFW methods e.g. [`Window.setTitle`](https://godoc.org/github.com/go-gl/glfw/v3.3/glfw#Window.SetTitle).

**Comment by ekuusi** [comment]
So how do I get access to the GlfwWindow? *Application has IWindow which it says is the "Embedded GlfwWindow", but I can't figure how to access the GlfwWindow methods.
