### ISSUE TITLE
Consider moving AddDefaultShaders inside NewRenderer 

### ISSUE THREAD

**Issue by ernstnaezer** [g3n/engine#21]
Hi, 

I've just spend a couple of hours trying to figure out why a particular shader wasn't loaded. In the end it turned out my app didn't call `AddDefaultShaders`. 

On the up-side, I now understand GoLang a lot better and I figured out the logger system 👍 But, since it is supposed to register the defaults, let's make it default - batteries included.

**Comment by danaugrs** [comment]
Hi - good point. `renderer.AddDefaultShaders()` is now called automatically by the cross-platform `app` implementations: https://github.com/g3n/engine/commit/4242aa5ceb48a67e32c210482021c45b720fc384.
