### ISSUE TITLE
Unclear how to properly dispose of nodes

### ISSUE THREAD

**Issue by ekuusi** [g3n/engine#218]
Not really an issue, but rather a question.

I'm disposing of nodes with scene.remove and then nulling the slice that contained references to the nodes, like so:

```
func (a *animator) clearNodeGroup(nodes []*core.Node) []*core.Node {

	for _, node := range nodes {
		a.scene.Remove(node)
	}
	nodes = nil

	return nodes
}


a.clearNodeGroup(a.allLines)
```

However, I seem to be running into memory issues over time, so I'm not sure if I need to do something else to dispose of the nodes. Haven't been able to figure out anything else that would cause the slowdowns and memory problems. If the scene is on pause, not insterting / removing any nodes, it can run for ages.

**Comment by gremour** [comment]
Just stumbled upon this library. Here's my advice from the Go language point of view.

You're passing nodes as a variable copy to this function. Nulling it has no effect (it's a local variable). You need to remove the reference to variable you pass to this function (i.e. assign it to nil) to let GC collect it.

If I understand correctly your use case, here's an example:
```go
type Animator{
    allLines []*core.Node
}

// ...

a.clearNodeGroup(a.allLines)
a.allLines = nil
```

**Comment by danaugrs** [comment]
This might have been fixed by https://github.com/g3n/engine/pull/214. Closing tentatively. Please reopen if you encounter this again!
