### ISSUE TITLE
Combining multiple geometries into a single mesh?

### ISSUE THREAD

**Issue by JMTyler** [g3n/engine#229]
Let me start by stating clearly that I am new to game development and don't really know what I'm doing.  (Although I am not new to Go, or development in general.)

I'm trying to build a voxel-based game.  My understanding is a lot of optimisation here comes from figuring out which voxels can be combined into a single mesh and then reducing which polygons within that mesh need to be rendered.

Since, in G3N, a mesh can only contain a single geometry, I was hoping there might be a way to merge multiple geometries into one super geometry, then build the mesh around _that_.  Perhaps this isn't the right way to handle my voxel problem?  But I think this feature would still be valuable in other scenarios as well.

Is this something that can already be done and I'm just missing it?  Is it something you are planning to add?  Do you have any recommendations for workarounds I can use to achieve this, or a better direction to take?

**Comment by danaugrs** [comment]
Hi Jared! Welcome 👋

Building a voxel-based game should be a lot of fun.

You can build your entire voxel world using a single mesh/graphic/geometry if you like. You need to specify the vertices, faces, normals, UVs, etc. You can assign different materials to different parts of the geometry using geometry groups. You can modify the geometry dynamically, as frequently as you like. There's no need to have multiple geometry objects associated with the same mesh as far as I can think/remember.

I'd start by creating a data structure containing voxel grid data and initially rendering each voxel as a separate cube mesh.
When you feel the need to optimize then you can transition into using larger meshes/geometries comprising multiple voxels each. In the future you could even predict which voxels are likely to be updated soon (e.g. the ones near the players) and keep those as cube meshes. There are lots of cool optimizations.

Even if all your voxels are cube meshes, you can already do several significant optimizations using the voxel data structure e.g. not rendering voxels that are fully surrounded.

Here is a nice resource with some ideas on building voxel-based environments: https://sites.google.com/site/letsmakeavoxelengine/home

Let me know if you have any more questions!

**Comment by JMTyler** [comment]
Thanks so much Daniel, your feedback and the link you recommended have been incredibly useful!  I've made a lot of progress as a result.

I'm facing an issue with multi-materials, however.  I'm grouping my voxels into chunks, such that the chunk is a single geometry despite being many voxels, which has improved performance dramatically since each chunk only requires to make a single draw call.  However, that only works when a chunk contains a single material (which is unrealistic in this style of voxel world).  As soon as I switch it over to using multiple materials, it returns to making one drawcall per voxel.

I assume this is because I am adding all the indices of each individual voxel as a distinct group, and it is probably actually making one drawcall per _group_, which would certainly make sense.

Is there any way to have the engine merge groups that share the same material, right before rendering them?  Or is that just something that I should roll up my sleeves & do on my end (i.e. only create a new group if there isn't one for a given material, otherwise add the voxel's indices to the existing group for that material)?  The latter would be non-trivial since groups only contain sequential indices, whereas my chunks' indices are only currently grouped by voxel, so there's nothing ensuring that all indices sharing the same material will be next to each other in the array.  Obviously I can do that if it's the right way to go, but it's enough work that I don't want to spend the time on it if it's _not_ the right way to go. :P

Or, as usual, if I'm completely missing the mark and there's a better solution to this multi-material problem, please feel free to enlighten me. :)

**Comment by JMTyler** [comment]
Actually, don't waste your time answering that... After writing it I realised making one group per material in a chunk is obviously the correct solution, and not actually as hard as I was making it out to be, so I just went ahead and coded it.  And it's working great! :+1:

**Comment by danaugrs** [comment]
You got it right, good to hear it's working! You'll get the hang of G3N in no time 😄
As always, let me know if you have any questions.
