### ISSUE TITLE
obj decoder doesn't load texture

### ISSUE THREAD

**Issue by chriscamacho** [g3n/engine#23]
dcdr, err := obj.Decode("piece.obj", "piece.mtl")
    if err != nil {
        log.Fatal("Error:%s loading obj (piece)", err)
    }
    msh,err := dcdr.NewMesh(&dcdr.Objects[0])
    if err != nil {
        panic(err)
    }

where piece.mtl points to a texture file in the same directory

even "manually" adding a texture to the mesh doesn't work

    tex1, err := texture.NewTexture2DFromImage("warrior.png")
    if err != nil {
        log.Fatal("Error:%s loading warrior.png texture", err)
    }
    mat1 := material.NewStandard(math32.NewColor(1, 1, 1))
    mat1.AddTexture(tex1)
    msh.AddMaterial(mat1,0,1)`

The object is well lit and appears plain white.

**Comment by leonsal** [comment]
We added support in the [engine](https://github.com/g3n/engine) for the obj decoder to load textures and  tests in [g3nd](https://github.com/g3n/g3nd) (loader/obj) which loads cube with textures.

**Comment by chriscamacho** [comment]
still doesn't work...
