### ISSUE TITLE
Is bounding box for geometry type object oriented?

### ISSUE THREAD

**Issue by NataliaDobosz** [g3n/engine#233]
Does BoundigBox() method for Geometry type calculates axis-aligned or object oriented bounding box?

**Comment by danaugrs** [comment]
Hi! Geometry's `BoundingBox()` computes the axis-aligned bounding box in the geometry's reference frame.
If you transform the object that is using that geometry and you want to find the axis-aligned bounding box in the global reference frame you need to apply the world matrix. Here's an example of how we do this in the renderer:

https://github.com/g3n/engine/blob/6d0136f3444c35f7c4d4189575b815562c30b3ef/renderer/renderer.go#L236-L238
