### ISSUE TITLE
Installation error due to formatting

### ISSUE THREAD

**Issue by SamTov** [g3n/engine#235]
**System**

*  Mac intel 64
*  Darwin 20.4.0

It seems that there is an error with the audio directory file listener-browser. When I run the install as `GOOS=js GOARCH=wasm go install ./...` I get the following

```sh
# github.com/g3n/engine/audio
audio/listener-browser.go:44:1: missing return at end of function
audio/listener-browser.go:50:1: missing return at end of function
audio/listener-browser.go:62:1: missing return at end of function
```

If I then remove these methods as they are all under a `//TODO` comment I will get the error
```sh
audio/listener-browser.go:11:2: imported and not used: "github.com/g3n/engine/gls"
audio/listener-browser.go:12:2: imported and not used: "github.com/g3n/engine/math32"
```

Removing the imports results in a build with no comments. I am somewhat unsure of how successfully the build is as there are no comments at all. Perhaps having some messaging to say that a build was successful would be helpful. 

Also, I am unsure if this install error is unique to me, but if not, would it be better to put this listener-browser stuff into its own branch?

**Comment by SamTov** [comment]
I'd definitely be interested. I'll need to do some digging for a while first though.

**Comment by danaugrs** [comment]
Closing to consolidate WebAssembly discussion in https://github.com/g3n/engine/issues/114.
