### ISSUE TITLE
Demos (and example code) displaying in quarter of window scene

### ISSUE THREAD

**Issue by amlwwalker** [g3n/engine#241]
All the demos, and any code I find around here/the web are rendering in bottom left quarter of generated window/scene. Any ideas why?
Whats strange though is the mouse detection is in the correct place

github.com/g3n/engine v0.1.1-0.20210723144827-abef212b4d1

in the following picture, my mouse clicked where im pointing (the screenshot hides the actual mouse)
![image](https://user-images.githubusercontent.com/2920180/129794548-aa4d20fc-d345-45a6-b480-57ea169037d4.png)

![image](https://user-images.githubusercontent.com/2920180/129794624-010e56c6-9ef3-4a85-bc0f-5edb4bbb5d66.png)

**Comment by danaugrs** [comment]
Hi! Unfortunately I don't have a Mac.
Mac folks might be able to help: @mat007 @SamTov
It would be awesome if we could get scaling working well on Mac.

**Comment by SamTov** [comment]
Could you send me some script to run to see if I can reproduce it?

**Comment by amlwwalker** [comment]
OK so I have actually reinstalled the libraries and I think it was because I was pulling some code from master and some from the tag as master hadn't been tagged. It seems I cant reproduce this now
