### ISSUE TITLE
Go Report Card for G3N

### ISSUE THREAD

**Issue by justinclift** [g3n/engine#25]
Went to add this to the [Awesome-Go](https://github.com/avelino/awesome-go) list, however the Go Report Card for g3n/engine isn't pretty at the moment. :wink:

&nbsp; &nbsp; https://goreportcard.com/report/github.com/g3n/engine

Any interest in cleaning up the bits's it's complaining about?  Most of them seem to be "low hanging fruit" (eg pretty easy to resolve).

**Comment by danaugrs** [comment]
We will work on it! Check again in a few weeks. 😉

**Comment by quillaja** [comment]
This is still a pretty awesome project. I'm just getting started playing with it, but it seems it's pretty much exactly what I was looking for--an easy to use 3d engine. I'm not terribly interested in games, just rendering things. Thanks!

**Comment by danaugrs** [comment]
We have an A+ now!
I sent a [pull request](https://github.com/avelino/awesome-go/pull/1933) to [awesome-go](https://github.com/avelino/awesome-go).
