### ISSUE TITLE
Audio dependency names for CentOS 7

### ISSUE THREAD

**Issue by justinclift** [g3n/engine#26]
Just read the audio dependencies for CentOS in the README.md, so decided to investigate quickly:

> For CentOS/Fedora-like Linux distributions, install libopenal1 and libvorbisfile3 (to be verified)

On my CentOS 7 x64 desktop, the needed package for OpenAL seems to be called "openal-soft" (available in the standard EPEL repo) instead of "libopenal1".  There is a matching "openal-soft-devel" package too, but it doesn't *seem* to be needed when testing just now.

For testing, I compiled [g3nplay](https://github.com/g3n/demos/tree/master/g3nplay) and ran it with the demo .ogg and .wav files.

* Without `openal-soft` installed, an error message `Error trying to load OpenAL library` is displayed.
* With just `openal-soft` installed (without the -devel package too) the .wav files (only) play back fine.
* Adding the `openal-soft-devel` didn't seem to change anything.  The .wav files played back fine again.

For the .ogg demo files though, nothing seemed to work.  Both the `libvorbis` and `libogg` packages were already installed on my desktop, but the .ogg files refused to play.  As in, the `g3nplay` application proceeded as if there were... but no sound of any sort.  Add the `libogg-devel` and `libvorbis-devel` packages then recompiling g3nplay didn't change anything.

So... for at least the OpenAL stuff the package name is pretty clear.  Not real sure about the libvorbis bits though. :wink:

**Comment by leonsal** [comment]
1. We will change the reference of `libopenal1` to `openal-soft` for CentOS in the README.

2. Does CentOS has the `libvorbisfile3` package ?
In Debian/Ubuntu this package depends on `libvorbis` and `libogg`,
so installing it also installs `libvorbis` and `libogg`.
This package is need by `G3N` as it contains high-level functions for reading `OggVorbis` encoded audio files.

3. The development packages are not needed for any of these libraries since
the header files are included internally in `G3N`.

**Comment by justinclift** [comment]
Checking now, CentOS 7 doesn't seem to have `libvorbisfile3` package available in the standard repositories:

```
$ sudo yum list|grep -i vorbis
libvorbis.i686                          1:1.3.3-8.el7                  @base    
libvorbis.x86_64                        1:1.3.3-8.el7                  @anaconda
libvorbis-devel.i686                    1:1.3.3-8.el7                  base     
libvorbis-devel.x86_64                  1:1.3.3-8.el7                  base     
libvorbis-devel-docs.noarch             1:1.3.3-8.el7                  base     
mingw32-libvorbis.noarch                1.3.4-1.el7                    epel     
mingw64-libvorbis.noarch                1.3.4-1.el7                    epel     
vorbis-tools.x86_64                     1:1.4.0-12.el7                 base
```

Doing some searching online for about it to gain a better understanding... all that's really showing up is the Debian and Ubuntu package pages for it:

* https://packages.debian.org/stretch/libvorbisfile3
* https://launchpad.net/ubuntu/+source/libvorbis

Taking another approach, the standard `libvorbis` package in CentOS 7 (and Fedora too it seems) already contains a `libvorbisfile` library:

```
$ rpm -ql libvorbis|sort
/usr/lib64/libvorbisenc.so.2
/usr/lib64/libvorbisenc.so.2.0.9
/usr/lib64/libvorbisfile.so.3
/usr/lib64/libvorbisfile.so.3.3.5
/usr/lib64/libvorbis.so.0
/usr/lib64/libvorbis.so.0.4.6
/usr/lib/libvorbisenc.so.2
/usr/lib/libvorbisenc.so.2.0.9
/usr/lib/libvorbisfile.so.3
/usr/lib/libvorbisfile.so.3.3.5
/usr/lib/libvorbis.so.0
/usr/lib/libvorbis.so.0.4.6
/usr/share/doc/libvorbis-1.3.3
/usr/share/doc/libvorbis-1.3.3
/usr/share/doc/libvorbis-1.3.3/COPYING
/usr/share/doc/libvorbis-1.3.3/COPYING
```

I'm kind of guessing... but it seems like the `libvorbis` package on CentOS/Fedora might already have the needed bits.  Might not be a seperate package needed.

That being said... I have no idea why .ogg files aren't playing through g3nplay, but .wav files are.

**Comment by leonsal** [comment]
Does `ldconfig` find `libvorbisfile` ?
In my Linux Mint the command returns:
```
>ldconfig -p | grep libvorbisfile
	libvorbisfile.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3
```

**Comment by justinclift** [comment]
Yep:

```
$ ldconfig -p|grep -i libvorbisfile
        libvorbisfile.so.3 (libc6,x86-64) => /lib64/libvorbisfile.so.3
        libvorbisfile.so.3 (libc6) => /lib/libvorbisfile.so.3
```

Note that I have both 32 and 64-bit versions installed, as the desktop itself is 64-bit but I have Steam also installed.  Steam is 32-bit only, so pulled in a bunch of 32-bit versions of things when installing.

Just to check if it makes any difference, I removed the 32-bit version of `libvorbis`, compiled g3nplay again and tried out the .ogg files.  Still no go:

```
$ go build main.go
$ ./main Vivaldi1.wav 
OpenAL Community version: 1.1 ALSOFT 1.16.0
Xiph.Org libVorbis 1.3.3
Playing:[Vivaldi1.wav] (62.0 seconds)
^C
$ ./main Bach1.ogg 
OpenAL Community version: 1.1 ALSOFT 1.16.0
Xiph.Org libVorbis 1.3.3
^C
```

Hmmm, looking at the output from those two runs, it clearly could process the .wav file as it shows the name and expected runtime.  Not so for the .ogg.

I can try attaching a debugger to it later on today and see if anything interesting shows up as a difference.  Hopefully it's something simple. :smile:

**Comment by justinclift** [comment]
Oh, as a data point, the [g3nd](https://github.com/g3n/g3nd) demo program also hangs when playing any of the audio demos.  The visual-only ones work completely fine however.

Completely guessing here, but it's probably going to be the same root cause, whatever that turns out to be. :smile:

**Comment by leonsal** [comment]
We committed a new version of G3N and G3ND. Now the installation of the audio libraries dependencies is compulsory. We updated the README.md with these dependencies.
What was probably happening previously was that we were compiling G3N with internal `libogg/libvorbis` headers for an specific version (1.3.2/1.3.5) but the user's installed version was different.
I noticed that in CentOS 7 the `libvorbis` version is 1.3.3 but in Ubuntu/Mint is 1.3.5. This probably crashed the program when a function of the library was called.

**Comment by justinclift** [comment]
Thanks @leonsal.  I'll recompile and see if the audio now plays.  If it does, that'll pretty much confirm that was the problem. :smile:

**Comment by justinclift** [comment]
Excellent news, the audio now works!

Btw, the required devel packages for building on CentOS 7 seem to be `libvorbis-devel` and `openal-soft-devel`.  No need to specifically request `libogg-devel`, as the `libvorbis-devel` package pulls it in automatically as a dependency.

Note - tried with and without each of them just to make sure.  Those two above are definitely the correct ones. :smile:

Thanks for getting this done!

**Comment by justinclift** [comment]
Ahhhh, just noticed you've already updated the README.md with that info.  Cool. 😄
