### ISSUE TITLE
Expected "f" in "ShiftRight" word

### ISSUE THREAD

**Issue by solv1k** [g3n/engine#264]
https://github.com/g3n/engine/blob/00f54a0d42f425179b555b510d358403560ba359/window/canvas.go#L270

**Comment by fwflunky** [comment]
lmao

**Comment by mrjrieke** [comment]
rofl -- coders

**Comment by danaugrs** [comment]
Lmao :joy: fixed in https://github.com/g3n/engine/commit/7b89285c3b47893d5555ae6994dd7b0294061f57.
