### ISSUE TITLE
Minor README.md bug?

### ISSUE THREAD

**Issue by justinclift** [g3n/engine#27]
Reading over the example on the README.md quickly, before trying it out (probably later today), one of the comments seems outdated:

```
// OpenGL functions must be executed in the same thread where
// the context was created (by window.New())
	runtime.LockOSThread()
```

On the second line it mentions `window.New()`, however there isn't a call to `window.New()` in the example.  Should that be `window.Manager()`?

**Comment by leonsal** [comment]
fixed

**Comment by justinclift** [comment]
Excellent @leonsal. :smile:
