### ISSUE TITLE
How to Convert screen mouse coordinates to world coordinates? 

### ISSUE THREAD

**Issue by 529124368** [g3n/engine#273]

**Comment by Juuliuus** [comment]
try this math for game developers video:
https://www.youtube.com/watch?v=zZM2uUkEoFw&list=PLW3Zl3wyJwWOpdhYedlD-yCB7WQoHf-My&index=14

**Comment by danaugrs** [comment]
The raycasting example in g3nd does this: https://github.com/g3n/g3nd/blob/master/demos/other/raycast.go
