### ISSUE TITLE
Is there a way to crop images?

### ISSUE THREAD

**Issue by 529124368** [g3n/engine#274]

**Comment by 529124368** [comment]
Is there a way to crop pictures in G3N? Because when I need to do the game UI, I need to dynamically transform a blood cell picture to achieve the effect of adding blood and reducing blood.

**Comment by danaugrs** [comment]
You can probably achieve the same effect by manipulating panels, e.g. putting a panel on top of another to hide the one below. You might be able to modify the panel's UV coordinates, although I'm not sure if that's exposed.
