### ISSUE TITLE
Is the project still under mantainance?

### ISSUE THREAD

**Issue by Goproxer** [g3n/engine#277]
As the title suggests.

**Comment by danaugrs** [comment]
Hey, you can take a look at https://github.com/g3n/engine/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc to have an idea of the activity. I try to review and merge PRs at least once every month.

**Comment by Goproxer** [comment]
> Hey, you can take a look at https://github.com/g3n/engine/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc to have an idea of the activity. I try to review and merge PRs at least once every month.

Thx! Happy that the project is still expanding.
