### ISSUE TITLE
MacOS: GLAPI Error

### ISSUE THREAD

**Issue by ZhaoyangChen** [g3n/engine#28]
When I try to run the demo, it gives the error as follow:

`GLAPI Error: 1281 calling: glLineWidth`

**Comment by justinclift** [comment]
As a thought towards finding out the problem, does this help? https://github.com/g3n/engine/issues/19#issuecomment-321131486

**Comment by justinclift** [comment]
Oh, this looks like similar to https://github.com/g3n/engine/pull/18#issuecomment-321907133.  That Pull Request seems like it's meant to fix the problem.

**Comment by ZhaoyangChen** [comment]
Looks like somewhat related.  I will try again after it's merged. Thanks for your reply.

**Comment by danaugrs** [comment]
This issue has been addressed by https://github.com/g3n/engine/commit/1929d6070113634d2d0ac653b6c3bcf67bf4033a.
