### ISSUE TITLE
MacOS: fuzzy font on Retina

### ISSUE THREAD

**Issue by dant3** [g3n/engine#280]
I'm trying to run an example from the readme.md of the engine on a mac.
The button text looks really fuzzy. Looks as if some antialiasing is missing. Most likely the problem is because Retina is not supported. My system is MacBook Pro (16-inch, 2019).

![image](https://user-images.githubusercontent.com/820057/183708619-e47073e4-3da1-4d52-800e-ce5571abec27.png)

P.S. Sorry for the camera photo, but there is no way I can demonstrate this with the screenshot -- since the problem is caused by Retina.

**Comment by danaugrs** [comment]
Yeah, this is probably because of the lack of HDPI support and maybe also due to non-pixel perfect alignment of the font. PRs are welcome, although https://github.com/g3n/engine/issues/281 should probably be tackled first.

**Comment by qizhanchan** [comment]
Any Updates?
