### ISSUE TITLE
Ready for a game?

### ISSUE THREAD

**Issue by rucuriousyet** [g3n/engine#31]
I've been using Love2D to write a MMORPG with some RTS features but I've been noticing a huge performance drop just drawing around 100x100 tilegrids on a larger display... I would love to switch to a Go-based option, but I'm having trouble finding something that I like and that works. Should I use this or would I be better off just using something else? (I may use OpenGL since I don't really need anything to complex... just textures, some lighting/blurring shaders and text)

**Comment by justinclift** [comment]
As a data point, this was written using G3N:

&nbsp; &nbsp; https://github.com/danaugrs/gokoban

Not exactly at the scale of a MMORG though. :smile:

**Comment by danaugrs** [comment]
@rucuriousyet Cool! G3N is mostly focused on 3D graphics but you could certainly make a 2D game with it.
Go is definitely a good choice for an MMORPG server, and having server-client language consistency is always good. You can try making a prototype and see how it goes - we'd love to see it!

**Comment by justinclift** [comment]
Hmmm, for a 2D specific project then https://github.com/therecipe/qt might also be feasible.

The primary developer seems to have gotten over their initial burst of enthusiasm though, so not sure how bright the future is for that project just yet.

**Comment by quillaja** [comment]
github.com/faiface/pixel is a pretty easy-to-use 2D opengl-based graphics library that does the things you mentioned @rucuriousyet .
