### ISSUE TITLE
Problem creating a window outside of main.go

### ISSUE THREAD

**Issue by happilymarrieddad** [g3n/engine#33]
Hey Guys,

I can't seem to create a window outside of main.go.
Operating System: Linux Mint 18.3

If I copy and paste the sample it works perfectly.
When I remove everything except the window it works perfectly
If I move the window code into a package and run it I get the following error
```
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: cannot open file /usr/local/go/pkg/linux_amd64/github.com/g3n/engine/window.a: open /usr/local/go/pkg/linux_amd64/github.com/g3n/engine/window.a: no such file or directory
```

Does not work
![selection_038](https://user-images.githubusercontent.com/6416323/37420942-b68ce7c8-277d-11e8-8267-4f69441fd374.png)
![selection_039](https://user-images.githubusercontent.com/6416323/37420945-b85ecbca-277d-11e8-8b25-34aef874d36f.png)

Works just fine
![selection_040](https://user-images.githubusercontent.com/6416323/37421011-dea711e8-277d-11e8-93c3-542170162278.png)

**Comment by happilymarrieddad** [comment]
I don't think it's a namespace thing because this doesn't work as well.

![selection_041](https://user-images.githubusercontent.com/6416323/37421135-25e40912-277e-11e8-9d75-1883023384dc.png)
![selection_042](https://user-images.githubusercontent.com/6416323/37421140-275c5e70-277e-11e8-9b6d-bb3b45474b9f.png)

**Comment by danaugrs** [comment]
Hi! Thanks for using g3n!
Your directory structure looks very non-kosher for a Go project.
You should have a top level `src`, `bin`, and `pkg` directories under your `GOPATH` root.
Reading this should help: [Organizing Go Code](https://golang.org/doc/code.html#Organization).
Let me know if you still are having trouble after updating your directory structure!

**Comment by happilymarrieddad** [comment]
@danaugrs yea you are correct. Thanks man!

**Comment by happilymarrieddad** [comment]
This was fixed by upgrading to go1.10 and then fixing my paths
