### ISSUE TITLE
Does "graphic.Skybox" work?

### ISSUE THREAD

**Issue by quillaja** [g3n/engine#34]
I tried using `graphic.Skybox` (made via `NewSkybox()`) and I couldn't figure out how to make it work. It displays the images as expected, but cuts off the other geometry in the scene (in this case some terrain). I tried increasing the size via `SetScale()` but that didn't change anything.

The demo in g3nd creates the skybox manually instead of using the one supplied in the engine.

Thanks

**Comment by danaugrs** [comment]
I just checked in a fix that [disables the depthMask for the Skybox](https://github.com/g3n/engine/commit/bafcbdb8df1ea0a71ec00390e9e533a8a503e4b3#diff-42a5a5bfb9c680f0b47a3488c36d2b98). It should always be rendered in the background now. The [earth g3nd demo](https://github.com/g3n/g3nd/blob/master/shader/earth.go) has an example usage if you need it but it looks like you have it working. Try again and let me know if you have any further issues!

**Comment by quillaja** [comment]
I pulled the update and `graphic.Skybox` works as expected now. Thanks a lot for taking care of that! I saw the todo in the code and wondered if that was the issue. =)
