### ISSUE TITLE
Small example program showing just a button

### ISSUE THREAD

**Issue by jameycribbs** [g3n/engine#4]
Any chance of creating a small example program that just puts a button on the screen, or maybe a line of text?

I have been trying to piece together something like this using the demo program on the g3n git page and pulling in code from the button demo on the demo program git page, but I know nothing about opengl so I have no idea what I'm doing.  So far, my attempts at doing this have failed.  Since I am mainly interested in using this library for gui programming, I would love to see a simple example program that just throws a button or a label on the screen that would show me how to use just the gui parts of this library.

**Comment by leonsal** [comment]
We created a new repository for standalone demos: https://github.com/g3n/demos.
Try out: `go get github.com/g3n/demos/gui_button`

Regards

**Comment by jameycribbs** [comment]
Exactly what I was looking for!  Thank you so much!
