### ISSUE TITLE
Animation Support

### ISSUE THREAD

**Issue by Splizard** [g3n/engine#45]
Loading collada/gltf2.0 animations, is this on the roadmap?
How difficult would this be to implement?

This is perhaps the only thing missing from this engine :+1:

**Comment by danaugrs** [comment]
Hi! We just added support for loading static glTF models (PBR and all) including node-based animations.
I also added support for morph targets and am planning to add support for loading glTF morph target animations soon 😄

**Comment by danaugrs** [comment]
Very nice! It's great to see a more complex (and cool) node animation than the ones I used for dev/testing!

Support for morph animations is almost done, there are only a few remaining bugs.
Morphing is independent from skeletal animations, but skeletal animations are coming right after! (along with glTF loading of them)

I've recently started planning and working on a complex multiplayer game with g3n (an RTS!) that will absolutely require skeletal animations (and many other things) and it will definitely help drive the development of g3n and new features.

**Comment by danaugrs** [comment]
Alright folks - glTF loading of morph animations is now working!
You can see it by loading the AnimatedMorphCube in the glTF loader demo in g3nd.
Please let me know if you try loading other glTF morph animations (or make some using the g3n API), and whether they work or not!
Onward to skeletal animations!

**Comment by danaugrs** [comment]
Support for skeletal animations is mostly done and working! See the glTF loader demo for an example. 

There is one remaining issue with certain models where some bones don't behave correctly but I haven't been able to figure out why so far. For example if you load this [dancing stormtrooper](https://sketchfab.com/models/12bd08d66fe04a84be446e583d6663ac), you'll see he keeps his hands stretched out when they should be closed. If anyone figures it out please let me know or make a PR!
