### ISSUE TITLE
Can't install the engine

### ISSUE THREAD

**Issue by Nickan** [g3n/engine#46]
Hi after running "go get -u github.com/g3n/engine/...", it throws error like this:
```
# github.com/go-gl/glfw/v3.2/glfw
In file included from go/src/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:24:0:
go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/internal.h:169,
                 from go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_init.c:28,
                 from go/src/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I did install all the necessary packages, I am running Ubuntu 18.04 LTS, Go 1.10.1 in VirtualBox.

**Comment by chriscamacho** [comment]
you'll need Xorg development packages installed as its compiling glfw, glfw's website is a little unspecific here... http://www.glfw.org/docs/latest/compile.html#compile_deps_x11

**Comment by Nickan** [comment]
I already did AFAIK, "sudo apt-get install xorg-dev", so should do the "Generating build files with CMake."? Or I guess I am clearly missing something? Thanks for the help in advance.

**Comment by Jldevictoria** [comment]
@Nickan Did you every get a resolution to this?  I have the same issue on Ubuntu 18.04 after installing all the required libraries.

**Comment by danaugrs** [comment]
@Nickan looks like the issue might be related to https://github.com/go-gl/glfw. I'd try getting the minimal example code in their [README.md](https://github.com/go-gl/glfw/blob/master/README.md) working first. When you get that working then come back and try installing G3N again.

@dmitshur any idea what might be causing this, and should we open an issue?

**Comment by Jldevictoria** [comment]
I think this line is where the issue comes from: (src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42)

Seems like it might be some new change to the glfw repo, and not g3n

![image](https://user-images.githubusercontent.com/6485853/53991468-8254f000-40df-11e9-89c0-59ba5734e786.png)

**Comment by Jldevictoria** [comment]
https://stackoverflow.com/questions/51534284/how-to-circumvent-format-truncation-warning-in-gcc  Need to check, but as this is a warning, this might actually be installed correctly.  I will get back to you.

**Comment by Jldevictoria** [comment]
@danaugrs Have you tested g3n through X11 over SSH?  I'm wondering if this is due to me trying to run the application remotely?

When I try to run the hellog3n sample program I get 
![image](https://user-images.githubusercontent.com/6485853/53998677-6fe5b100-40f5-11e9-960d-eb20d71a8261.png)

I will let you know if I figure anything else out.

**Comment by danaugrs** [comment]
@Jldevictoria I have not tested over SSH. If you're still having trouble please open a new issue :)
