### ISSUE TITLE
Obtain monitor resolution

### ISSUE THREAD

**Issue by jameycribbs** [g3n/engine#5]
Is there a way to ask for the monitor resolution using your library?

That way, on high definition monitors, I could have my program scale up the window size and all the text sizes.

Thanks!

Jamey

**Comment by leonsal** [comment]
There is now:
```
// Open a window
win, err := window.New("glfw", 800, 600, "title", false)
swidth, sheight := win.GetScreenResolution(nil)

// Resize the window if necessary
win.SetSize(swidth, sheight)
```

**Comment by jameycribbs** [comment]
Perfect!  Thank you!
