### ISSUE TITLE
Don't link -ldl on FreeBSD

### ISSUE THREAD

**Issue by amyadzuki** [g3n/engine#50]
I'm trying to get any of the demos to work on FreeBSD.  I'm pretty new to golang so I can't submit a PR, but linking against -ldl breaks the build on FreeBSD.  On Linux, the dynamic loader is in a separate library called libdl but on FreeBSD it is built into the C standard library.  I am guessing that the problem is this: in g3n/engine/gls/build.go:12
```
// #cgo freebsd LDFLAGS: -ldl
```
should be changed to
```
// #cgo freebsd LDFLAGS: 
```

**Comment by danaugrs** [comment]
Thanks for the PRs!
