### ISSUE TITLE
remove dep on golang.org/x/image

### ISSUE THREAD

**Issue by finomxf** [g3n/engine#55]
hi team:

each time when I go get g3n, I need to copy golang.org's pkg by hand,  can we find a way to remove them?  many thanks! 

BR - fino 

$ go get -v -u github.com/g3n/engine/...
github.com/g3n/engine (download)
github.com/go-gl/glfw (download)
github.com/golang/freetype (download)
Fetching https://golang.org/x/image/math/fixed?go-get=1

https fetch failed: Get https://golang.org/x/image/math/fixed?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package github.com/g3n/engine/gui
	imports golang.org/x/image/math/fixed: unrecognized import path "golang.org/x/image/math/fixed" (https fetch: Get https://golang.org/x/image/math/fixed?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/image/font?go-get=1
https fetch failed: Get https://golang.org/x/image/font?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package github.com/g3n/engine/gui
	imports golang.org/x/image/font: unrecognized import path "golang.org/x/image/font" (https fetch: Get https://golang.org/x/image/font?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)

**Comment by rami-dabain** [comment]
Looks like you have an issue with your network / resolving
