### ISSUE TITLE
Serious graphical glitch involving resizing near the title bar of a GUI window widget

### ISSUE THREAD

**Issue by amyadzuki** [g3n/engine#63]
I have come across a really difficult-to-describe graphical glitch that I think occurs when you attempt to resize a GUI window widget near the title bar.

It is easiest to reproduce by resizing the top of a window downward in a short, rapid motion.  After the glitch is triggered, the window "runs away" from the mouse pointer whenever the mouse cursor approaches the title bar.

Another way to trigger the glitch is to resize the height from the bottom border of a GUI window widget as small as it gets, release the mouse button, and then enlarge the height back again in a short, rapid downward drag of the mouse.  Like before, after triggering it, the window "runs away" from the cursor whenever it approaches the title bar.

This glitch is serious because it causes GUI window widgets to "run off the screen" where they cannot be interacted with anymore.  Please let me know if you have any difficulty reproducing it and I will try to be more clear and/or supply example code as needed.

Tested on:
FreeBSD 10.3 amd64

**Comment by danaugrs** [comment]
Managed to reproduce it - an easy task given your clear instructions 😉.
I might take some time to refactor the entire window class.

**Comment by danaugrs** [comment]
I just checked-in a fix - let me know if you see any more weird behaviors!
Feel free to share any work-in-progress screenshots of your game when you get it going :)
