### ISSUE TITLE
GUI Window Widget Wishlist

### ISSUE THREAD

**Issue by amyadzuki** [g3n/engine#64]
I don't know if you get notifications for comments on closed issues, so just a quick note, I replied to https://github.com/g3n/engine/pull/61 and https://github.com/g3n/engine/pull/62 in the comments.

First of all, I am very happy with the current set of functionality, so these are all low priority suggestions.  But if you are reworking the window class, I feel like now is the time for me to mention a few ideas I had.

1.  Add an easy way to add an "X" close button widget in the upper right corner of the title bar of a window, on a per-window basis.

    1.  Allow us to register our own callback function to run when that close button is clicked, so that we can configure the behavior to not just close the window (maybe we want to ask them to save changes or something).

2.  You mentioned custom cursors for move and resize actions in https://github.com/g3n/engine/pull/62 and I really like that idea!  You said you already added it so maybe it doesn't belong on a wishlist...

3.  Add a way to close all open windows programmatically.

    1.  Perhaps additionally, a way to toggle all windows visible/invisible would be helpful too.  Maybe.

4.  Add methods to easily set the background color of the title bar and of the content area, without having to customize _everything_ at once by using styles.

Ok that's all I could come up with, do with them as you see fit.  Thanks for all your hard work on g3n!  I really appreciate everything you do :3

**Comment by danaugrs** [comment]
I just checked-in my window improvements. I fixed that annoying bug (https://github.com/g3n/engine/issues/63) and made resizing a lot more robust. Windows can now also be resized by their corners and diagonal resize cursors show up. Per your request, I added the option of having an "X" close button 😉  but it should probably be made more flexible - let me know when you start using it. Skipped item 3 - devs can worry about that for now.

I improved the window styling internals but styling in general could probably be enhanced across the board to make it easier to customize individual widgets of all kinds. Before we do that though there are some important GUI changes that need to be made, for example making sure all scrollable widgets use the scroller base class (https://github.com/g3n/engine/issues/69).

Looking forward to playing your game :)
