### ISSUE TITLE
Minor Enhancement: Could we have a SelectedAt() func on gui.DropDown?

### ISSUE THREAD

**Issue by SMerrony** [g3n/engine#70]
In larger applications dropdowns will typically be populated from arrays/slices.

It would require a lot less code in the application if we could simply get the row number back from a selected dropdown.  

We should take care of the case where a selection has not been made by returning either nil or -1 as the authors prefer.

**Comment by danaugrs** [comment]
I just merged https://github.com/g3n/engine/pull/71 which adds a SelectedPos() method which returns the index of the selected element or -1 if none selected.
