### ISSUE TITLE
[enhancement, minor] Subscribe to changes in Slider GUI widget

### ISSUE THREAD

**Issue by amyadzuki** [g3n/engine#73]
I would like to `.Subscribe` to changes in the `Slider` GUI widgets so that a callback I specify is called as the user changes the value.  I would use this to recalculate some things only when the slider is changed rather than every frame.

**Comment by MrWaggel** [comment]
Seems to be already implemented

https://github.com/g3n/engine/blob/db7282a2ba2381c4d72ddebdcabdfd376e585aaa/gui/slider.go#L145-L161

**Comment by danaugrs** [comment]
Thanks @amyadzuki and @MrWaggel. This is implemented now.
