### ISSUE TITLE
an .obj loader problem

### ISSUE THREAD

**Issue by SavostinVladimir** [g3n/engine#8]
Hello! Now I try to use your example "gopher3d" to experiment with loading other 3d models. I only change this string:
	`85     dec, err := obj.Decode("gopher.obj", "gopher.mtl")`

I write other names of other models, for example:

`85     dec, err := obj.Decode("KazSat2.obj", "KazSat2.mtl")`
or
`85     dec, err := obj.Decode("BasicCriypticman.obj", "BasicCriypticman.mtl")` , etc.

There is this models
[5721-osnovnoy-kriptitsmen.zip](https://github.com/g3n/engine/files/966659/5721-osnovnoy-kriptitsmen.zip)
[KazSat2.zip](https://github.com/g3n/engine/files/966660/KazSat2.zip)
[vanquish.zip](https://github.com/g3n/engine/files/966661/vanquish.zip)
3D-redactors opens them, it is ok!

But during copmilation errors occur:
```
GOROOT=C:/go
GOPATH=C:/GoProjects
C:/go\bin\go.exe build -i -o "C:\Users\ASUS\AppData\Local\Temp\Build main.go and rungo" C:/GoProjects/src/github.com/g3n/demos/gopher3d/main.go
"C:\Program Files (x86)\JetBrains\Gogland 171.3780.106\bin\runnerw.exe" "C:\Users\ASUS\AppData\Local\Temp\Build main.go and rungo"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x580df6]

goroutine 1 [running, locked to thread]:
github.com/g3n/engine/loader/obj.(*Decoder).parseUsemtl(0xc042094000, 0xc042089970, 0x1, 0x1, 0xc042089900, 0x2)
	C:/GoProjects/src/github.com/g3n/engine/loader/obj/obj.go:472 +0xb6
github.com/g3n/engine/loader/obj.(*Decoder).parseObjLine(0xc042094000, 0xc042089920, 0x11, 0xc042089920, 0x11)
	C:/GoProjects/src/github.com/g3n/engine/loader/obj/obj.go:305 +0x8db
github.com/g3n/engine/loader/obj.(*Decoder).(github.com/g3n/engine/loader/obj.parseObjLine)-fm(0xc042089920, 0x11, 0x649364, 0x4)
	C:/GoProjects/src/github.com/g3n/engine/loader/obj/obj.go:121 +0x45
github.com/g3n/engine/loader/obj.(*Decoder).parse(0xc042094000, 0x777520, 0xc042082038, 0xc042063dc8, 0x0, 0x0)
	C:/GoProjects/src/github.com/g3n/engine/loader/obj/obj.go:265 +0x182
github.com/g3n/engine/loader/obj.DecodeReader(0x777520, 0xc042082038, 0x777520, 0xc042082040, 0x0, 0x2, 0x3)
	C:/GoProjects/src/github.com/g3n/engine/loader/obj/obj.go:121 +0x27e
github.com/g3n/engine/loader/obj.Decode(0x64ef0e, 0x14, 0x64eefa, 0x14, 0x0, 0x0, 0x0)
	C:/GoProjects/src/github.com/g3n/engine/loader/obj/obj.go:104 +0x13d
main.main()
	C:/GoProjects/src/github.com/g3n/demos/gopher3d/main.go:85 +0xa8d

Process finished with exit code 2
```

**Comment by leonsal** [comment]
A commit was done that fixes the errors when loading the models.
But the decoding of the models materials is not quite correct yet,
showing wrong colors and materials properties.

You can get better results if you import the models using _Blender_ and
export again from Blender to `obj` or ` collada` format.
Blender has solved the quirks of decoding  the `obj` format and
when exporting follows the "standard" more closely.

A new standalone demo [g3nview](https://github.com/g3n/demos/tree/master/g3nview) was created
to view external models.

**Comment by SavostinVladimir** [comment]
Hi. Now it works. Ok, I will use Blender. 
Thank you!
