### ISSUE TITLE
Add ToolTip functionality

### ISSUE THREAD

**Issue by SMerrony** [g3n/engine#83]
Many GUI elements would benefit from having a .SetToolTip(string) method whereby if the user holds the mouse over the element for more than, say half a second, a tip or hint pops up.

**Comment by danaugrs** [comment]
@SMerrony I definitely agree we need to support tooltips. I left some comments in https://github.com/g3n/engine/pull/167 regarding the desired implementation. If anyone wants to tackle this, feel free.
