### ISSUE TITLE
Can't play Ogg Vorbis file

### ISSUE THREAD

**Issue by xyproto** [g3n/engine#9]
Hi,

I have an Ogg Vorbis audio file:

    % file test.ogg
    test.ogg: Ogg data, Vorbis audio, stereo, 48000 Hz, ~160000 bps, created by: Xiph.Org libVorbis I

It plays fine with `mpv`:

    % mpv test.ogg 
    Playing: test.ogg
     (+) Audio --aid=1 (vorbis 2ch 48000Hz)
    File tags:
     Artist: Vårsol
    AO: [pulse] 48000Hz stereo 2ch float
    A: 00:00:01 / 00:05:24 (0%)
    [...]
    Exiting... (Quit)
    ^C

However, when playing the file with these lines of code, I get a panic:

```go
	// Load Ogg Vorbis library
	err = vorbis.Load()
	if err != nil {
		panic(err)
	}
	fmt.Println(vorbis.VersionString())

	// Load audio
	player, err := audio.NewPlayer("test.ogg")
	if err != nil {
		panic(err)
	}

	// Play audio
	err = player.Play()
	if err != nil {
		panic(err)
	}
```

This is the output

```
Xiph.Org libVorbis 1.3.5
panic: Unsuported file type
```

This is on 64-bit Arch Linux with Go 1.8 and libvorbis 1.3.5 (comes with libvorbisfile: `/usr/lib/libvorbisfile.so.3.3.7`).

**Comment by xyproto** [comment]
Attaching `test.ogg` in a zip.
[test.zip](https://github.com/g3n/engine/files/981014/test.zip)

**Comment by leonsal** [comment]
Hi, you didn't send your whole program, so I can't see if you initialized the audio stack correctly.
See the function `loadAudioLibs` in [g3nd demo](https://github.com/g3n/g3nd/blob/master/main.go) which show how to initialize the audio.

I temporarily copied your `test.ogg` file to `g3nd` data directory and changed the  [audio_player demo](https://github.com/g3n/g3nd/blob/master/audio_player.go) to play your file and it worked ok.

**Comment by xyproto** [comment]
When compiling the g3nd demo application, using the latest sources, all the 3d samples seems to work fine. However, when clicking `audio` and then `player` the entire application hangs and I have to close it with `kill`.

I get this output in the terminal window:

```
./g3nd 
14:06:03.417459:I:G3ND:G3N Demo v0.1 starting
14:06:03.417496:I:G3ND:Using data directory:data
14:06:03.493598:I:G3ND:OpenGL version: 3.3 (Core Profile) Mesa 17.0.5
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
14:06:03.611626:I:G3ND:OpenAL Community version: 1.1 ALSOFT 1.17.2
14:06:03.611990:I:G3ND:Xiph.Org libVorbis 1.3.5
```

Audio works great in Chromium, games, audacity, mpv etc.

I don't have jack installed, nor started.

**Comment by leonsal** [comment]
We committed a new standalone demo: [g3nplay](https://github.com/g3n/demos/tree/master/g3nplay) which shows how to play a sound file from the command line.

We have some problems with _OpenAL_ freezing sporadically but it only occurs when we start and stop an audio demo many times. But it is a rare event. We currently use version 1.16 which comes with Linux Mint 18.1 but we built version 17.2 from source and had no problems. If you could build _OpenAL_ from source we recommend to built it without the _JACK_ back end by removing the jack library development package (`libjack-dev` for Debian/Ubuntu/Mint) from your system and rebuilding _OpenAL_. It will at least remove the spurious messages generated by _OpenAL_ at the start up.

**Comment by xyproto** [comment]
When using `g3nplay` I no audio and the following output:

```
% ./g3nplay test.ogg
connect(2) call to /dev/shm/jack-1197/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
OpenAL Community version: 1.1 ALSOFT 1.17.2
Xiph.Org libVorbis 1.3.5
```

When using `mpv`, there is audio (it is using pulse audio):

```
AO: [pulse] 48000Hz stereo 2ch float
```

I thought the error message about jack was the problem, so I wrote a small test-program in C, snipping code from various OpenAL examples and documentation:

[openaldevicetest](https://github.com/xyproto/openaldevicetest/blob/c0cbed8678f2984bc0cfc433ebfd1ce40b6ce053/main.c)

To my surprise, the jack error message does not seem to be related, because the `alcOpenDevice` function call completes successfully and returns a device.

The output from the `openaldevicetest` is:

```
Enumerating OpenAL audio devices:
---------------------------------
0: OpenAL Soft
---------------------------------
Opening OpenAL audio device "OpenAL Soft":
connect(2) call to /dev/shm/jack-1197/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
OpenAL: Could successfully open a device
Done.
```

It seems like OpenAL isn't discovering and using pulseaudio or alsa, both for my laptop and for my desktop system (both 64-bit Arch Linux using `openal 1.17.2`).

Also:
* Adding `/etc/openal/alsoft.conf` with `drivers=pulse,alsa` made no difference.
* I have no `.alsoftrc` file in my home directory.
* I tried rebuiling openal with `-D ALSOFT_REQUIRE_PULSEAUDIO=ON` and `-D ALSOFT_BACKEND_PULSEAUDIO=ON` but this made no difference.
* Rebuilding openal in a chroot (normal practice) without any jack package installed did not help and curiously the message about `/dev/shm/jack-1197/default/jack_0` is still there. I tried removing and recompiling all the g3n libraries for go and recompiling g3nplay.
* Rebuilding openal with `ALSOFT_BACKEND_JACK=OFF` removed the message about `/dev/shm/jack-1197/default/jack_0`, but there is no audio from ` g3nplay`.

Do you happen to know of a test-program for openal written in C that will just play a sound and that's it?

**Comment by leonsal** [comment]
In the `openal soft` package there are the following test programs:
- `openal-info` - Shows information about available devices
- `altonegen` - Plays a 1Khz sine wave tone.

Follows the output of `openal-info` for my system:
```
Available playback devices:
    ALSA Default
    HDA Intel PCH, ALC887-VD Analog (CARD=PCH,DEV=0)
    HDA Intel PCH, ALC887-VD Digital (CARD=PCH,DEV=1)
    HDA NVidia, HDMI 0 (CARD=NVidia,DEV=3)
    HDA NVidia, HDMI 1 (CARD=NVidia,DEV=7)
    HDA NVidia, HDMI 2 (CARD=NVidia,DEV=8)
    HDA NVidia, HDMI 3 (CARD=NVidia,DEV=9)
Available capture devices:
    ALSA Default
    HDA Intel PCH, ALC887-VD Analog (CARD=PCH,DEV=0)
    HDA Intel PCH, ALC887-VD Alt Analog (CARD=PCH,DEV=2)
    HD Webcam C615, USB Audio (CARD=C615,DEV=0)
Default playback device: ALSA Default
Default capture device: ALSA Default
ALC version: 1.1

** Info for device "ALSA Default" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE,
    ALC_EXT_DEDICATED, ALC_EXT_disconnect, ALC_EXT_EFX,
    ALC_EXT_thread_local_context, ALC_SOFTX_device_clock, ALC_SOFT_HRTF,
    ALC_SOFT_loopback, ALC_SOFT_pause_device
Available HRTFs:
    default-44100.mhr
    default-48000.mhr
    default-44100.mhr #2
    default-48000.mhr #2
OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.17.2
OpenAL extensions:
    AL_EXT_ALAW, AL_EXT_BFORMAT, AL_EXT_DOUBLE, AL_EXT_EXPONENT_DISTANCE,
    AL_EXT_FLOAT32, AL_EXT_IMA4, AL_EXT_LINEAR_DISTANCE, AL_EXT_MCFORMATS,
    AL_EXT_MULAW, AL_EXT_MULAW_BFORMAT, AL_EXT_MULAW_MCFORMATS, AL_EXT_OFFSET,
    AL_EXT_source_distance_model, AL_LOKI_quadriphonic,
    AL_SOFT_block_alignment, AL_SOFT_buffer_samples, AL_SOFT_buffer_sub_data,
    AL_SOFT_deferred_updates, AL_SOFT_direct_channels, AL_SOFT_loop_points,
    AL_SOFT_MSADPCM, AL_SOFT_source_latency, AL_SOFT_source_length
EFX version: 1.0
Max auxiliary sends: 4
Supported filters:
    Low-pass, High-pass, Band-pass
Supported effects:
    EAX Reverb, Reverb, Chorus, Distortion, Echo, Flanger, Ring Modulator,
    Compressor, Equalizer, Dedicated Dialog, Dedicated LFE
```
Output of `altonegen` (plays a tone)
```
Opened "OpenAL Soft"
Playing 1000hz sine-wave tone with 44100hz sample rate and 44100hz output, for 5 seconds...
4...
3...
2...
1...
```

**Comment by xyproto** [comment]
`altonegen` works perfectly here, both for the official `openal` package and for the one I recompiled that does not show an error message about `jack`.

```
Opened "OpenAL Soft"
Playing 1000hz sine-wave tone with 48000hz sample rate and 48000hz output, for 5 seconds...
4...
3...
2...
1...
```

**Comment by xyproto** [comment]
`openal-info` output:

```
Available playback devices:
    Built-in Audio Analog Stereo
Available capture devices:
    Built-in Audio Analog Stereo
    Monitor of Built-in Audio Analog Stereo
Default playback device: Built-in Audio Analog Stereo
Default capture device: Built-in Audio Analog Stereo
ALC version: 1.1

** Info for device "Built-in Audio Analog Stereo" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE,
    ALC_EXT_DEDICATED, ALC_EXT_disconnect, ALC_EXT_EFX,
    ALC_EXT_thread_local_context, ALC_SOFTX_device_clock, ALC_SOFT_HRTF,
    ALC_SOFT_loopback, ALC_SOFT_pause_device
Available HRTFs:
    default-44100.mhr
    default-48000.mhr
OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.17.2
OpenAL extensions:
    AL_EXT_ALAW, AL_EXT_BFORMAT, AL_EXT_DOUBLE, AL_EXT_EXPONENT_DISTANCE,
    AL_EXT_FLOAT32, AL_EXT_IMA4, AL_EXT_LINEAR_DISTANCE, AL_EXT_MCFORMATS,
    AL_EXT_MULAW, AL_EXT_MULAW_BFORMAT, AL_EXT_MULAW_MCFORMATS, AL_EXT_OFFSET,
    AL_EXT_source_distance_model, AL_LOKI_quadriphonic,
    AL_SOFT_block_alignment, AL_SOFT_buffer_samples, AL_SOFT_buffer_sub_data,
    AL_SOFT_deferred_updates, AL_SOFT_direct_channels, AL_SOFT_loop_points,
    AL_SOFT_MSADPCM, AL_SOFT_source_latency, AL_SOFT_source_length
EFX version: 1.0
Max auxiliary sends: 4
Supported filters:
    Low-pass, High-pass, Band-pass
Supported effects:
    EAX Reverb, Reverb, Chorus, Distortion, Echo, Flanger, Ring Modulator,
    Compressor, Equalizer, Dedicated Dialog, Dedicated LFE

```

**Comment by leonsal** [comment]
Currently no ideas...
You can try to put some `Println()`  statements in the `OpenAL` Go binding at:
[al.go](https://github.com/g3n/engine/tree/master/audio/al/al.go) to try to identify where the problem initially occurs.

The player is implemented by [player.go](https://github.com/g3n/engine/blob/master/audio/player.go) and uses the Go binding to access _OpenAL_.
Try to identify exactly after which call the system freezes.

Also try to play a wave file instead of _Ogg Vorbis_ so only `OpenAL` would be used...

**Comment by xyproto** [comment]
* Tried playing a wave file instead. Same result, no audio (but `altonegen` works).
* Tried using the master branch of OpenAL. Same result, no audio (but `altonegen` works).

Will try the `Println()` suggestion. I am also planning to try the previous version of OpenAL, version 1.16.

**Comment by xyproto** [comment]
OpenAL 1.16 made no difference.

However, playing 16 bit wav worked:

    test3.wav:    RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 48000 Hz

But not these:

```
test.wav:     RIFF (little-endian) data, WAVE audio, Microsoft PCM, 24 bit, stereo 48000 Hz
test3_32.wav: RIFF (little-endian) data, WAVE audio, mono 48000 Hz
test.ogg:     Ogg data, Vorbis audio, stereo, 48000 Hz, ~160000 bps, created by: Xiph.Org libVorbis I
test2.ogg:    Ogg data, Vorbis audio, stereo, 48000 Hz, ~160000 bps, created by: Xiph.Org libVorbis I
test3.ogg:    Ogg data, Vorbis audio, mono, 48000 Hz, ~96000 bps, created by: Xiph.Org libVorbis I
test3_16.ogg: Ogg data, Vorbis audio, mono, 48000 Hz, ~96000 bps, created by: Xiph.Org libVorbis I
```

I used audacity to create the ogg files.

Does .ogg files created with audacity play for you?

**Comment by leonsal** [comment]
I imported a wave file into _Audacilty_ and exported as an _Ogg_ file and it played OK.

**Comment by xyproto** [comment]
I see, thanks.

Since the `RIFF (little-endian) data, WAVE audio, Microsoft PCM, 24 bit, stereo 48000 Hz` file didn't play here, I guess the next action is to figure out why it doesn't want to play with `g3nplay` on: 64-bit Arch Linux + OpenAL 1.17 + Go 1.8,

probably looking into `al.go`, as you mentioned above.
