### ISSUE TITLE
Next "Getting Started" pieces?

### ISSUE THREAD

**Issue by justinclift** [g3n/engine#92]
There doesn't yet seem to be anything for new developers after the initial "Getting Started" code piece, to show them how to do more interesting things.

While g3nd has tonnes of functionality, the g3nd app layer itself adds a huge bunch of obfuscation making it really, really hard to see wtf is going on. :frowning:

As a potential direction forward, I took some time to pull apart `g3nd.Create()` and the `other.points` demo, throwing them into a much simplified repo:

https://github.com/justinclift/pointsDemo

Note - my attempt there isn't fantastic code, it's just a concept piece for discussion.  Quite a lot of it is probably duplicated from the g3n engine's defaults, and the `Initialize()` code should probably be moved into `main()` too. :smile:

The concept I'm trying to convey is that there seems to be a need for further beginner things, but they'd be better off self contained without the g3nd abstraction layer to confuse things.

Optimally, there would be some kind of web or wiki page which comes after the current "Getting Started" page/code, and guides people how to use the new things shown in this next piece of code.

Thoughts? :smile:

**Comment by chriscamacho** [comment]
I've done some simple getting started stuff including mouse picking, you're welcome to agregate the code from by blog (bedroomcoders.co.uk) if you're wanting to make some extra stuff for beginners, I have to say though the g3n demo application is very useful for learning....

**Comment by justinclift** [comment]
Thanks. :smile:

Yeah, I'm kind of thinking that g3n could really do with some expansion on the wiki.  Guiding people from the super basic example presented in the repo Readme through to maybe showing off each of the things in demo application.

Not actually sure if I'll get to it myself though (ugh).  Too many things to get done in the near future, although there is some likely g3n stuff in there. :smile:

**Comment by justinclift** [comment]
@chriscamacho Just created a new "Guides and Tutorials" page on the wiki (so far) listing your 4 articles. :smile:

https://github.com/g3n/engine/wiki/Guides-and-Tutorials

Also added pointers to that page from what looks like the right places in the wiki.

If you know of other good tutorials/articles for g3n, would you be ok to add them to the list?

Hmm, thinking about it more, we should probably point to the wiki from the main repo readme too.

**Comment by danaugrs** [comment]
I definitely agree - I've been meaning to expand the wiki for a while. I asked @amyadzuki if she could help with a Getting Started page and she started the outline (Thanks Amy!). It's often hard to step back and write tutorials but it can be very rewarding (and also help review and improve the engine architecture and API). I'll increase the tutorials priority in my mind and try to get to them.

**Comment by amyadzuki** [comment]
No problem!  I still plan to do a lot more I've just been a bit busy with my own game lately.  I see lots of changes, it's looking great!
