### ISSUE TITLE
GUI: Underline of active tab always on top

### ISSUE THREAD

**Issue by SMerrony** [g3n/engine#97]
This is a bit hard to describe, so a picture is attached, but there seems to be a kind of underline under the active tab label in a tabbar which always displays on top of everything else in the GUI.

![tabartifact](https://user-images.githubusercontent.com/10760350/44626814-28e35b80-a91b-11e8-9147-b824af080728.PNG)

In the screen grab you can see the line from the tabbar on top of the window drawn over it.  The same effect is visible when menus drop-down over the tabbar.

**Comment by danaugrs** [comment]
@SMerrony sorry for the delay. I believe this might have been fixed - please reopen if not.
