### ISSUE TITLE
Camera rotation not updating Look Value

### ISSUE THREAD

**Issue by Flexin1981** [g3n/engine#98]
When updating the direction that a camera is pointing using the underlying node functions the look value is not updated.

`func (n *Node) SetRotationX(x float32)`
`func (n *Node) SetRotationY(y float32)`
`func (n *Node) SetRotationZ(z float32)`

This is making it difficult to control the rotation of the camera as I have no value that I am aware of I can use to find the orientation of the camera once these functions are used.

**Comment by danaugrs** [comment]
See https://github.com/g3n/engine/pull/99#issuecomment-531613727.
